version: '3.7'

services:
  grpc:
    build: ./Technology.gRPC
    ports:
      - "5001:80"
  react:
    build: ./Technology.React
    ports:
      - "5000:80"
  api:
    build: ./Technology.Api
    ports:
      - "5002:80"